use std::{
    env,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

fn add_link_search_if_exists(dir: &Path) {
    if dir.is_dir() {
        println!("cargo:rustc-link-search=native={}", dir.display());
    }
}

fn find_first_existing_libdir(prefix: &Path) -> Option<PathBuf> {
    let candidates = [
        prefix.join("lib"),
        prefix.join("lib64"),
        prefix.join("build").join("lib"),
        prefix.join("build").join("lib64"),
        prefix.join("build"),
    ];
    candidates.into_iter().find(|p| p.is_dir())
}

fn list_static_lib_names(libdir: &Path) -> Vec<String> {
    let mut names = Vec::new();
    let Ok(entries) = fs::read_dir(libdir) else {
        return names;
    };

    for e in entries.flatten() {
        let path = e.path();
        if path.extension() != Some(OsStr::new("a")) {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if let Some(stripped) = stem.strip_prefix("lib") {
            names.push(stripped.to_string());
        }
    }

    names.sort();
    names.dedup();
    names
}

fn write_unified_wrapper(
    out_dir: &Path,
    crate_dir: &Path,
    llama_src: &Path,
    want_mtmd: bool,
) -> PathBuf {
    let wrapper_path = out_dir.join("wrapper_unified.h");

    let wrapper_h = crate_dir.join("wrapper.h");
    if !wrapper_h.exists() {
        panic!("wrapper.h not found at {}", wrapper_h.display());
    }

    let mut contents = String::new();
    contents.push_str("#pragma once\n\n");
    contents.push_str("// Auto-generated by build.rs: unified bindgen wrapper\n\n");
    contents.push_str(&format!("#include \"{}\"\n", wrapper_h.display()));

    if want_mtmd {
        let mtmd_h = llama_src.join("tools/mtmd/mtmd.h");
        if !mtmd_h.exists() {
            panic!(
                "mtmd feature enabled, but mtmd.h not found at {}",
                mtmd_h.display()
            );
        }
        contents.push_str(&format!("\n#include \"{}\"\n", mtmd_h.display()));

        let mtmd_helper_h = llama_src.join("tools/mtmd/mtmd-helper.h");
        if !mtmd_helper_h.exists() {
             panic!(
                "mtmd feature enabled, but mtmd-helper.h not found at {}",
                mtmd_helper_h.display()
            );
        }
        contents.push_str(&format!("\n#include \"{}\"\n", mtmd_helper_h.display()));
    }

    fs::write(&wrapper_path, contents).expect("failed to write wrapper_unified.h");
    wrapper_path
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=wrapper.h");

    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let llama_src = crate_dir.join("vendor/llama.cpp");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    let want_mtmd = env::var_os("CARGO_FEATURE_MTMD").is_some();
    let want_metal = env::var_os("CARGO_FEATURE_METAL").is_some();
    let want_cuda = env::var_os("CARGO_FEATURE_CUDA").is_some();

    if want_metal && want_cuda {
        panic!("features `metal` and `cuda` are mutually exclusive; pick one");
    }

    println!(
        "cargo:rerun-if-changed={}",
        llama_src.join("include/llama.h").display()
    );
    if want_mtmd {
        println!(
            "cargo:rerun-if-changed={}",
            llama_src.join("tools/mtmd/mtmd.h").display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let unified_wrapper = write_unified_wrapper(&out_dir, &crate_dir, &llama_src, want_mtmd);
    println!("cargo:rerun-if-changed={}", unified_wrapper.display());

    let mut builder = bindgen::Builder::default()
        .header(unified_wrapper.to_string_lossy())
        .clang_arg(format!("-I{}", llama_src.join("include").display()))
        .clang_arg(format!("-I{}", llama_src.join("ggml/include").display()))
        .clang_arg(format!("-I{}", llama_src.join("tools/mtmd").display()))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()));

    builder = builder
        .allowlist_function("llama_.*")
        .allowlist_type("llama_.*")
        .allowlist_var("LLAMA_.*");

    if want_mtmd {
        builder = builder
            .allowlist_function("mtmd_.*")
            .allowlist_type("mtmd_.*")
            .allowlist_var("MTMD_.*");
    }

    let bindings = builder
        .generate()
        .expect("bindgen failed (do you have clang + libclang installed?)");

    let bindings_path = out_dir.join("bindings.rs");
    fs::write(&bindings_path, bindings.to_string()).expect("failed to write bindings.rs");

    // ---- CMake: build llama.cpp ----
    let mut cfg = cmake::Config::new(&llama_src);
    cfg.define("BUILD_SHARED_LIBS", "OFF");

    cfg.define("LLAMA_BUILD_TESTS", "OFF");
    cfg.define("LLAMA_BUILD_EXAMPLES", "OFF");
    cfg.define("LLAMA_BUILD_SERVER", "OFF");

    cfg.define("LLAMA_BUILD_TOOLS", if want_mtmd { "ON" } else { "OFF" });

    cfg.define("GGML_METAL", "OFF");
    cfg.define("GGML_CUDA", "OFF");

    if want_cuda {
        cfg.define("GGML_CUDA", "ON");
    }

    if want_metal {
        if target_os != "macos" {
            panic!("feature `metal` only makes sense on macOS");
        }
        cfg.define("GGML_METAL", "ON");
        cfg.define("GGML_ACCELERATE", "ON");
    }

    let _ = target_arch;

    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    if profile.eq_ignore_ascii_case("release") {
        cfg.define("CMAKE_BUILD_TYPE", "Release");
    } else {
        cfg.define("CMAKE_BUILD_TYPE", "Debug");
    }

    let dst = cfg.build();

    // ---- Link: locate lib dir and emit link directives ----
    add_link_search_if_exists(&dst.join("lib"));
    add_link_search_if_exists(&dst.join("lib64"));
    add_link_search_if_exists(&dst.join("build"));
    add_link_search_if_exists(&dst.join("build").join("lib"));
    add_link_search_if_exists(&dst.join("build").join("lib64"));

    let libdir = find_first_existing_libdir(&dst).unwrap_or_else(|| {
        panic!(
            "Could not find library output directory under CMake prefix {}",
            dst.display()
        )
    });

    let libs = list_static_lib_names(&libdir);
    let has = |name: &str| libs.iter().any(|x| x == name);

    if want_mtmd && has("mtmd") {
        println!("cargo:rustc-link-lib=static=mtmd");
    }

    if has("llama") {
        println!("cargo:rustc-link-lib=static=llama");
    } else {
        eprintln!(
            "warning: libllama not found in {}; libs: {:?}",
            libdir.display(),
            libs
        );
    }

    for lib in libs {
        if lib == "llama" || lib == "mtmd" {
            continue;
        }
        if lib.starts_with("ggml") {
            println!("cargo:rustc-link-lib=static={}", lib);
        }
    }

    if target_os == "macos" {
        println!("cargo:rustc-link-lib=c++");
    } else if target_os == "linux" {
        println!("cargo:rustc-link-lib=stdc++");
    }

    if target_os == "macos" {
        println!("cargo:rustc-link-lib=framework=Accelerate");

        if want_metal {
            println!("cargo:rustc-link-lib=framework=Foundation");
            println!("cargo:rustc-link-lib=framework=Metal");
            println!("cargo:rustc-link-lib=framework=MetalKit");
            println!("cargo:rustc-link-lib=framework=MetalPerformanceShaders");
        }
    }
}
